---
id: ApplicationsAreRunningInVirtualizedEnvironments
title: Applications are running in virtualized environments
risk: Through a vulnerability in one service on a server, the attacker gains access
  to other services running on the same server.
measure: Applications are running in a dedicated and isolated virtualized environments.
difficultyOfImplementation:
  knowledge: 3
  time: 3
  resources: 5
usefulness: 3
samm2: o-environment-management|A|1
iso27001-2017:
- virtual environments are not explicitly covered by ISO 27001 - too specific
- 13.1.3
...
