---
risk: Standard hardening practices for cloud environments are not performed leading
  to vulnerabilities.
measure: With the help of tools the configuration of virtual environments are tested.
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 1
usefulness: 4
level: 2
implementation:
- <a href="https://github.com/aquasecurity/kube-bench">kube-bench</a>
samm: EH2-B
samm2: v-security-testing|A|1
iso27001-2017:
- system hardening is not explicitly covered by ISO 27001 - too specific
- 12.6.1
- 14.2.3
- 14.2.8
id: TestTheClouldConfiguration
...
