---
risk: Local stored logs can be unauthorized manipulated by attackers with system access
  or might be corrupt after an incident. In addition, it is hard to perform an correlation
  of logs. This leads attacks, which can be performed silently.
measure: A centralized logging system is used and applications logs (including application
  exceptions) are shipped to it.
difficultyOfImplementation:
  knowledge: 1
  time: 1
  resources: 1
usefulness: 5
dependsOn:
- Visualized logging
- Alerting
samm: SA2-B
samm2: o-incident-management|A|1
iso27001-2017:
- not explicitly covered by ISO 27001 - too specific
- 12.4.1
title: Centralized application logging
id: CentralizedApplicationLogging
...
