---
risk: While a deployment is performed, the application can not be reached.
measure: A deployment without downtime is performed*.
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 2
usefulness: 2
implementation: Docker, Webserver, rolling update
dependsOn:
- Defined deployment process
samm2: i-secure-deployment|A|1
iso27001-2017:
- 12.5.1
- 14.2.2
- 17.2.1
title: Rolling update on deployment
id: RollingUpdateOnDeployment
...
