---
risk: Time pressure and ignorance might lead to false predictions for the test intensity.
measure: The intensity of the used tools are not modified to safe time.
difficultyOfImplementation:
  knowledge: 1
  time: 1
  resources: 1
usefulness: 1
level: 1
samm2: v-security-testing|A|1
iso27001-2017:
- 12.6.1
- 14.2.1
- 14.2.5
id: DefaultSettingsForIntensity
...
