---
risk: Scans might use a too small or too high test intensity.
measure: A testing concept considering the amount of time per scan/intensity is created
  and applied. A dynamic analysis needs more time than a static analysis. The dynamic
  scan, depending on the test intensity might be performed on every commit, every
  night, every week or once in a month.
difficultyOfImplementation:
  knowledge: 3
  time: 3
  resources: 3
usefulness: 2
samm2: v-security-testing|A|2
iso27001-2017:
- 14.2.2
- 14.2.3
- 14.2.1
- 14.2.5
- 12.6.1
title: Creation and application of a testing concept
id: CreationAndApplicationOfATestingConcept
...
