---
id: TestOfTheConfigurationOfCloudEnvironments
title: Test of the configuration of cloud environments
risk: Standard hardening practices for cloud environments are not performed leading
  to vulnerabilities.
measure: With the help of tools the configuration of virtual environments are tested.
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 1
usefulness: 4
implementation:
- <a href='https://github.com/aquasecurity/kube-hunter'>kube-hunter</a>
- openVAS
samm: EH2-B
iso27001-2017:
- system hardening is not explicitly covered by ISO 27001 - too specific
- 12.6.1
- 14.2.3
- 14.2.8
...
