dimension:
  name: Test and Verification
  subdimension:
    level-1: []
    level-2:
    - comment: 'The integration of module tests takes place during development instead,
        it highlights vulnerabilities in sub-routines, functions, modules, libraries
        etc. checked.

        A sample implementation of unit tests are explained in the video [Shift-Left-Security
        with the Security Test Pyramid - Andreas Falk](https://www.youtube.com/watch?v=TzFZy3f7d8E)
        starting with minute 9.

        '
      difficultyOfImplementation:
        knowledge: 3
        resources: 2
        time: 4
      implementation:
      - $ref: data/dimensions-subdimensions-activities/implementations.yaml#/implementations/junit
      - $ref: data/dimensions-subdimensions-activities/implementations.yaml#/implementations/karma
      iso27001-2017:
      - 14.2.3
      - 14.2.8
      level: 2
      measure: Usage of unit tests to test important security related features like
        authentication and authorization.
      name: Security unit tests for important components
      risk:
      - Vulnerabilities are rising due to code changes.
      samm2: V-ST-3-B
      usefulness: 3
    level-3:
    - difficultyOfImplementation:
        knowledge: 3
        resources: 2
        time: 4
      implementation:
      - $ref: data/dimensions-subdimensions-activities/implementations.yaml#/implementations/httpunit
      iso27001-2017:
      - 14.2.3
      - 14.2.8
      level: 3
      measure: Implementation of essential security related integration tests. For
        example for authentication and authorization.
      name: Security integration tests for important components
      risk:
      - Vulnerabilities are rising due to code changes in a complex microservice environment.
      samm2: V-ST-3-B
      usefulness: 2
    level-4:
    - difficultyOfImplementation:
        knowledge: 5
        resources: 3
        time: 5
      implementation: []
      iso27001-2017:
      - 14.2.3
      - 14.2.8
      level: 4
      measure: Implementation of security related tests via unit tests and integration
        tests. Including the test of libraries, in case the are not tested already.
      name: High coverage of security related module and integration tests
      risk:
      - Vulnerabilities are rising due to code changes in a complex microservice environment
        in not important components.
      samm2: V-ST-3-B
      usefulness: 3
    - dependsOn:
      - Defined deployment process
      difficultyOfImplementation:
        knowledge: 2
        resources: 2
        time: 2
      implementation: []
      iso27001-2017:
      - 14.2.3
      - 14.2.8
      level: 4
      measure: Integration tests are performed against the production environment
        after each deployment.
      name: Smoke Test
      risk:
      - During a deployment an error might happen which leads to non-availability
        of the system, a part of the system or a feature.
      samm2: V-ST-3-B
      usefulness: 2
    name: Application tests
