---
risk: People are not looking into tests results. Vulnerabilities not recolonized,
  even they are detected by tools.
measure: All defects from the dimension Test- and Verification are instrumented.
difficultyOfImplementation:
  knowledge: 3
  time: 3
  resources: 2
usefulness: 4
dependsOn:
- Simple application metrics
- Visualized metrics
samm2: o-incident-management|A|2
iso27001-2017:
- 12.6.1
title: Advanced webapplication metrics
id: AdvancedWebapplicationMetrics
...
