---
risk: Attackers who compromise source code can see confidential access information
  like database credentials.
measure: Configuration parameters are set for each environment not in the source code.
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 1
usefulness: 4
implementation: ""
samm: SA2-A
samm2: i-secure-deployment|B|1
iso27001-2017:
- 9.4.5
- 14.2.6
id: EnvironmentDependingConfigurationParameters
...
