---
risk: Denial of service (internally by an attacker or unintentionally by a bug) on
  one service effects other services
measure: All virtual environments are using resource limits on hard disks, memory
  and CPU
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 3
usefulness: 3
level: 2
dependsOn:
- Applications are running in virtualized environments
samm2: o-environment-management|A|1
iso27001-2017:
- virtual environments are not explicitly covered by ISO 27001 - too specific
- 12.1.3
- 13.1.3
- 17.2.1
id: VirtualEnvironmentsAreLimited
...
