---
risk: Attacks on an application are not recognized.
measure: Gathering of application metrics helps to identify incidents like brute force
  attacks, login/logout.
difficultyOfImplementation:
  knowledge: 2
  time: 2
  resources: 2
usefulness: 5
implementation: Prometheus
samm2: o-incident-management|A|1
iso27001-2017:
- 12.4.1
id: SimpleApplicationMetrics
...
