name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.hub.docker.com
          username: wurstbrot
          password: ${{ secrets.HUB_TOKEN }}
      - name: create and push an image
        run: |
          if [ "${GITHUB_REF##*/}" == "master" ]; then
            VERSION="3.0.0-${GITHUB_RUN_NUMBER}"
          else
            BRANCH_TO_DOCKER=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
            VERSION="${BRANCH_TO_DOCKER}-${GITHUB_RUN_NUMBER}"
          fi
          docker build -t wurstbrot/dsomm:latest .
          docker push wurstbrot/dsomm:latest
          docker tag  wurstbrot/dsomm:${VERSION}
          docker push wurstbrot/dsomm:${VERSION}
