name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write
  issues: read


jobs:
  build:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: 'master'
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Semantic Release Version
        id: get-version
        run: echo "::set-output name=version::$(grep -oP '\[\d+\.\d+\.\d+\]' CHANGELOG.md | tr -d '[]')"

      - name: show version
        run: |
          echo "Semantic Release Version: ${{ steps.get-version.outputs.version }}"

      - name: setup qemu for multi-arch build
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.hub.docker.com
          username: wurstbrot
          password: ${{ secrets.HUB_TOKEN }}
      - name: create and push yaml image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile-yaml
          platforms: linux/amd64,linux/arm64
          tags: wurstbrot/dsomm-yaml-generation:${{ steps.get-version.outputs.version }},wurstbrot/dsomm-yaml-generation:latest
      - name: create and push dsomm image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: wurstbrot/dsomm:${{ steps.get-version.outputs.version }},wurstbrot/dsomm:latest
      - uses: actions/checkout@v3
      # Commit all changed files back to the repository with code signing
      - uses: planetscale/ghcommit-action@v0.1.8
        with:
          commit_message: "🤖 fmt"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
