name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write
  issues: read
  #pull-requests: write # to be able to comment on released pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # This is important if you have branch protection rules!
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ""
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Semantic Release Version
        id: get-version
        run: echo "::set-output name=version::$(grep -oP '\[\d+\.\d+\.\d+\]' CHANGELOG.md | tr -d '[]')"

      - name: show version
        run: |
          echo "Semantic Release Version: ${{ steps.get-version.outputs.version }}"

      - name: setup qemu for multi-arch build
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.hub.docker.com
          username: wurstbrot
          password: ${{ secrets.HUB_TOKEN }}
      - name: create and push yaml image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile-yaml
          platforms: linux/amd64,linux/arm64
          tags: wurstbrot/dsomm-yaml-generation:${{ steps.get-version.outputs.version }},wurstbrot/dsomm-yaml-generation:latest
      - name: create and push dsomm image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: wurstbrot/dsomm:${{ steps.get-version.outputs.version }},wurstbrot/dsomm:latest

